package pokemon.core;

public enum Move
{
    POUND("Pound", Type.NORMAL, MoveType.PHYSICAL, (byte)35, (short)40, (byte)100),
    KARATE_CHOP("Karate Chop", Type.FIGHTING, MoveType.PHYSICAL, (byte)25, (short)50, (byte)100),
    DOUBLESLAP("DoubleSlap", Type.NORMAL, MoveType.PHYSICAL, (byte)10, (short)15, (byte)85),
    COMET_PUNCH("Comet Punch", Type.NORMAL, MoveType.PHYSICAL, (byte)15, (short)18, (byte)85),
    MEGA_PUNCH("Mega Punch", Type.NORMAL, MoveType.PHYSICAL, (byte)20, (short)80, (byte)85),
    PAY_DAY("Pay Day", Type.NORMAL, MoveType.PHYSICAL, (byte)20, (short)40, (byte)100),
    FIRE_PUNCH("Fire Punch", Type.FIRE, MoveType.PHYSICAL, (byte)15, (short)75, (byte)100),
    ICE_PUNCH("Ice Punch", Type.ICE, MoveType.PHYSICAL, (byte)15, (short)75, (byte)100),
    THUNDERPUNCH("ThunderPunch", Type.ELECTRIC, MoveType.PHYSICAL, (byte)15, (short)75, (byte)100),
    SCRATCH("Scratch", Type.NORMAL, MoveType.PHYSICAL, (byte)35, (short)40, (byte)100),
    VICEGRIP("ViceGrip", Type.NORMAL, MoveType.PHYSICAL, (byte)30, (short)55, (byte)100),
    GUILLOTINE("Guillotine", Type.NORMAL, MoveType.PHYSICAL, (byte)5, (short)-1, (byte)-1),
    RAZOR_WIND("Razor Wind", Type.NORMAL, MoveType.SPECIAL, (byte)10, (short)80, (byte)100),
    SWORDS_DANCE("Swords Dance", Type.NORMAL, MoveType.STATUS, (byte)30, (short)-1, (byte)-1),
    CUT("Cut", Type.NORMAL, MoveType.PHYSICAL, (byte)30, (short)50, (byte)95),
    GUST("Gust", Type.FLYING, MoveType.SPECIAL, (byte)35, (short)40, (byte)100),
    WING_ATTACK("Wing Attack", Type.FLYING, MoveType.PHYSICAL, (byte)35, (short)60, (byte)100),
    WHIRLWIND("Whirlwind", Type.NORMAL, MoveType.STATUS, (byte)20, (short)-1, (byte)100),
    FLY("Fly", Type.FLYING, MoveType.PHYSICAL, (byte)15, (short)90, (byte)95),
    BIND("Bind", Type.NORMAL, MoveType.PHYSICAL, (byte)20, (short)15, (byte)85),
    SLAM("Slam", Type.NORMAL, MoveType.PHYSICAL, (byte)20, (short)80, (byte)75),
    VINE_WHIP("Vine Whip", Type.GRASS, MoveType.PHYSICAL, (byte)15, (short)35, (byte)100),
    STOMP("Stomp", Type.NORMAL, MoveType.PHYSICAL, (byte)20, (short)65, (byte)100),
    DOUBLE_KICK("Double Kick", Type.FIGHTING, MoveType.PHYSICAL, (byte)30, (short)30, (byte)100),
    MEGA_KICK("Mega Kick", Type.NORMAL, MoveType.PHYSICAL, (byte)5, (short)120, (byte)75),
    JUMP_KICK("Jump Kick", Type.FIGHTING, MoveType.PHYSICAL, (byte)10, (short)100, (byte)95),
    ROLLING_KICK("Rolling Kick", Type.FIGHTING, MoveType.PHYSICAL, (byte)15, (short)60, (byte)85),
    SAND_ATTACK("Sand-Attack", Type.GROUND, MoveType.STATUS, (byte)15, (short)-1, (byte)100),
    HEADBUTT("Headbutt", Type.NORMAL, MoveType.PHYSICAL, (byte)15, (short)70, (byte)100),
    HORN_ATTACK("Horn Attack", Type.NORMAL, MoveType.PHYSICAL, (byte)25, (short)65, (byte)100),
    FURY_ATTACK("Fury Attack", Type.NORMAL, MoveType.PHYSICAL, (byte)20, (short)15, (byte)85),
    HORN_DRILL("Horn Drill", Type.NORMAL, MoveType.PHYSICAL, (byte)5, (short)-1, (byte)-1),
    TACKLE("Tackle", Type.NORMAL, MoveType.PHYSICAL, (byte)30, (short)50, (byte)100),
    BODY_SLAM("Body Slam", Type.NORMAL, MoveType.PHYSICAL, (byte)15, (short)85, (byte)100),
    WRAP("Wrap", Type.NORMAL, MoveType.PHYSICAL, (byte)20, (short)15, (byte)90),
    TAKE_DOWN("Take Down", Type.NORMAL, MoveType.PHYSICAL, (byte)20, (short)90, (byte)85),
    THRASH("Thrash", Type.NORMAL, MoveType.PHYSICAL, (byte)10, (short)120, (byte)100),
    DOUBLE_EDGE("Double-Edge", Type.NORMAL, MoveType.PHYSICAL, (byte)15, (short)120, (byte)100),
    TAIL_WHIP("Tail Whip", Type.NORMAL, MoveType.STATUS, (byte)30, (short)-1, (byte)100),
    POISON_STING("Poison Sting", Type.POISON, MoveType.PHYSICAL, (byte)35, (short)15, (byte)100),
    TWINEEDLE("Twineedle", Type.BUG, MoveType.PHYSICAL, (byte)20, (short)25, (byte)100),
    PIN_MISSILE("Pin Missile", Type.BUG, MoveType.PHYSICAL, (byte)20, (short)14, (byte)85),
    LEER("Leer", Type.NORMAL, MoveType.STATUS, (byte)30, (short)-1, (byte)100),
    BITE("Bite", Type.DARK, MoveType.PHYSICAL, (byte)25, (short)60, (byte)100),
    GROWL("Growl", Type.NORMAL, MoveType.STATUS, (byte)40, (short)-1, (byte)100),
    ROAR("Roar", Type.NORMAL, MoveType.STATUS, (byte)20, (short)-1, (byte)100),
    SING("Sing", Type.NORMAL, MoveType.STATUS, (byte)15, (short)-1, (byte)55),
    SUPERSONIC("Supersonic", Type.NORMAL, MoveType.STATUS, (byte)20, (short)-1, (byte)55),
    SONICBOOM("SonicBoom", Type.NORMAL, MoveType.SPECIAL, (byte)20, (short)90, (byte)50),
    DISABLE("Disable", Type.NORMAL, MoveType.STATUS, (byte)20, (short)-1, (byte)100),
    ACID("Acid", Type.POISON, MoveType.SPECIAL, (byte)30, (short)40, (byte)100),
    EMBER("Ember", Type.FIRE, MoveType.SPECIAL, (byte)25, (short)40, (byte)100),
    FLAMETHROWER("Flamethrower", Type.FIRE, MoveType.SPECIAL, (byte)15, (short)95, (byte)100),
    MIST("Mist", Type.ICE, MoveType.STATUS, (byte)30, (short)-1, (byte)-1),
    WATER_GUN("Water Gun", Type.WATER, MoveType.SPECIAL, (byte)25, (short)40, (byte)100),
    HYDRO_PUMP("Hydro Pump", Type.WATER, MoveType.SPECIAL, (byte)5, (short)120, (byte)80),
    SURF("Surf", Type.WATER, MoveType.SPECIAL, (byte)15, (short)95, (byte)100),
    ICE_BEAM("Ice Beam", Type.ICE, MoveType.SPECIAL, (byte)10, (short)95, (byte)100),
    BLIZZARD("Blizzard", Type.ICE, MoveType.SPECIAL, (byte)5, (short)120, (byte)70),
    PSYBEAM("Psybeam", Type.PSYCHIC, MoveType.SPECIAL, (byte)20, (short)65, (byte)100),
    BUBBLEBEAM("BubbleBeam", Type.WATER, MoveType.SPECIAL, (byte)20, (short)65, (byte)100),
    AURORA_BEAM("Aurora Beam", Type.ICE, MoveType.SPECIAL, (byte)20, (short)65, (byte)100),
    HYPER_BEAM("Hyper Beam", Type.NORMAL, MoveType.SPECIAL, (byte)5, (short)150, (byte)90),
    PECK("Peck", Type.FLYING, MoveType.PHYSICAL, (byte)35, (short)35, (byte)100),
    DRILL_PECK("Drill Peck", Type.FLYING, MoveType.PHYSICAL, (byte)20, (short)80, (byte)100),
    SUBMISSION("Submission", Type.FIGHTING, MoveType.PHYSICAL, (byte)25, (short)80, (byte)80),
    LOW_KICK("Low Kick", Type.FIGHTING, MoveType.PHYSICAL, (byte)20, (short)-1, (byte)100),
    COUNTER("Counter", Type.FIGHTING, MoveType.PHYSICAL, (byte)20, (short)-1, (byte)100),
    SEISMIC_TOSS("Seismic Toss", Type.FIGHTING, MoveType.PHYSICAL, (byte)20, (short)-1, (byte)100),
    STRENGTH("Strength", Type.NORMAL, MoveType.PHYSICAL, (byte)15, (short)80, (byte)100),
    ABSORB("Absorb", Type.GRASS, MoveType.SPECIAL, (byte)25, (short)20, (byte)100),
    MEGA_DRAIN("Mega Drain", Type.GRASS, MoveType.SPECIAL, (byte)15, (short)40, (byte)100),
    LEECH_SEED("Leech Seed", Type.GRASS, MoveType.STATUS, (byte)10, (short)-1, (byte)90),
    GROWTH("Growth", Type.NORMAL, MoveType.STATUS, (byte)40, (short)-1, (byte)-1),
    RAZOR_LEAF("Razor Leaf", Type.GRASS, MoveType.PHYSICAL, (byte)25, (short)55, (byte)95),
    SOLARBEAM("SolarBeam", Type.GRASS, MoveType.SPECIAL, (byte)10, (short)120, (byte)100),
    POISONPOWDER("PoisonPowder", Type.POISON, MoveType.STATUS, (byte)35, (short)-1, (byte)75),
    STUN_SPORE("Stun Spore", Type.GRASS, MoveType.STATUS, (byte)30, (short)-1, (byte)75),
    SLEEP_POWDER("Sleep Powder", Type.GRASS, MoveType.STATUS, (byte)15, (short)-1, (byte)75),
    PETAL_DANCE("Petal Dance", Type.GRASS, MoveType.SPECIAL, (byte)10, (short)120, (byte)100),
    STRING_SHOT("String Shot", Type.BUG, MoveType.STATUS, (byte)40, (short)-1, (byte)95),
    DRAGON_RAGE("Dragon Rage", Type.DRAGON, MoveType.SPECIAL, (byte)10, (short)100, (byte)83),
    FIRE_SPIN("Fire Spin", Type.FIRE, MoveType.SPECIAL, (byte)15, (short)35, (byte)85),
    THUNDERSHOCK("ThunderShock", Type.ELECTRIC, MoveType.SPECIAL, (byte)30, (short)40, (byte)100),
    THUNDERBOLT("Thunderbolt", Type.ELECTRIC, MoveType.SPECIAL, (byte)15, (short)95, (byte)100),
    THUNDER_WAVE("Thunder Wave", Type.ELECTRIC, MoveType.STATUS, (byte)20, (short)-1, (byte)100),
    THUNDER("Thunder", Type.ELECTRIC, MoveType.SPECIAL, (byte)10, (short)120, (byte)70),
    ROCK_THROW("Rock Throw", Type.ROCK, MoveType.PHYSICAL, (byte)15, (short)50, (byte)90),
    EARTHQUAKE("Earthquake", Type.GROUND, MoveType.PHYSICAL, (byte)10, (short)100, (byte)100),
    FISSURE("Fissure", Type.GROUND, MoveType.PHYSICAL, (byte)5, (short)-1, (byte)-1),
    DIG("Dig", Type.GROUND, MoveType.PHYSICAL, (byte)10, (short)80, (byte)100),
    TOXIC("Toxic", Type.POISON, MoveType.STATUS, (byte)10, (short)-1, (byte)90),
    CONFUSION("Confusion", Type.PSYCHIC, MoveType.SPECIAL, (byte)25, (short)50, (byte)100),
    PSYCHIC("Psychic", Type.PSYCHIC, MoveType.SPECIAL, (byte)10, (short)90, (byte)100),
    HYPNOSIS("Hypnosis", Type.PSYCHIC, MoveType.STATUS, (byte)20, (short)-1, (byte)60),
    MEDITATE("Meditate", Type.PSYCHIC, MoveType.STATUS, (byte)40, (short)-1, (byte)-1),
    AGILITY("Agility", Type.PSYCHIC, MoveType.STATUS, (byte)30, (short)-1, (byte)-1),
    QUICK_ATTACK("Quick Attack", Type.NORMAL, MoveType.PHYSICAL, (byte)30, (short)40, (byte)100),
    RAGE("Rage", Type.NORMAL, MoveType.PHYSICAL, (byte)20, (short)20, (byte)100),
    TELEPORT("Teleport", Type.PSYCHIC, MoveType.STATUS, (byte)20, (short)-1, (byte)-1),
    NIGHT_SHADE("Night Shade", Type.GHOST, MoveType.SPECIAL, (byte)15, (short)-1, (byte)100),
    MIMIC("Mimic", Type.NORMAL, MoveType.STATUS, (byte)10, (short)-1, (byte)100),
    SCREECH("Screech", Type.NORMAL, MoveType.STATUS, (byte)40, (short)-1, (byte)85),
    DOUBLE_TEAM("Double Team", Type.NORMAL, MoveType.STATUS, (byte)15, (short)-1, (byte)-1),
    RECOVER("Recover", Type.NORMAL, MoveType.STATUS, (byte)10, (short)-1, (byte)-1),
    HARDEN("Harden", Type.NORMAL, MoveType.STATUS, (byte)30, (short)-1, (byte)-1),
    MINIMIZE("Minimize", Type.NORMAL, MoveType.STATUS, (byte)20, (short)-1, (byte)-1),
    SMOKESCREEN("SmokeScreen", Type.NORMAL, MoveType.STATUS, (byte)20, (short)-1, (byte)100),
    CONFUSE_RAY("Confuse Ray", Type.GHOST, MoveType.STATUS, (byte)10, (short)-1, (byte)100),
    WITHDRAW("Withdraw", Type.WATER, MoveType.STATUS, (byte)40, (short)-1, (byte)-1),
    DEFENSE_CURL("Defense Curl", Type.NORMAL, MoveType.STATUS, (byte)40, (short)-1, (byte)-1),
    BARRIER("Barrier", Type.PSYCHIC, MoveType.STATUS, (byte)30, (short)-1, (byte)-1),
    LIGHT_SCREEN("Light Screen", Type.PSYCHIC, MoveType.STATUS, (byte)30, (short)-1, (byte)-1),
    HAZE("Haze", Type.ICE, MoveType.STATUS, (byte)30, (short)-1, (byte)-1),
    REFLECT("Reflect", Type.PSYCHIC, MoveType.STATUS, (byte)20, (short)-1, (byte)-1),
    FOCUS_ENERGY("Focus Energy", Type.NORMAL, MoveType.STATUS, (byte)30, (short)-1, (byte)-1),
    BIDE("Bide", Type.NORMAL, MoveType.PHYSICAL, (byte)10, (short)-1, (byte)100),
    METRONOME("Metronome", Type.NORMAL, MoveType.STATUS, (byte)10, (short)-1, (byte)-1),
    MIRROR_MOVE("Mirror Move", Type.FLYING, MoveType.STATUS, (byte)20, (short)-1, (byte)-1),
    SELFDESTRUCT("Selfdestruct", Type.NORMAL, MoveType.PHYSICAL, (byte)5, (short)200, (byte)100),
    EGG_BOMB("Egg Bomb", Type.NORMAL, MoveType.PHYSICAL, (byte)10, (short)100, (byte)75),
    LICK("Lick", Type.GHOST, MoveType.PHYSICAL, (byte)30, (short)20, (byte)100),
    SMOG("Smog", Type.POISON, MoveType.SPECIAL, (byte)20, (short)20, (byte)70),
    SLUDGE("Sludge", Type.POISON, MoveType.SPECIAL, (byte)20, (short)65, (byte)100),
    BONE_CLUB("Bone Club", Type.GROUND, MoveType.PHYSICAL, (byte)20, (short)65, (byte)85),
    FIRE_BLAST("Fire Blast", Type.FIRE, MoveType.SPECIAL, (byte)5, (short)120, (byte)85),
    WATERFALL("Waterfall", Type.WATER, MoveType.PHYSICAL, (byte)15, (short)80, (byte)100),
    CLAMP("Clamp", Type.WATER, MoveType.PHYSICAL, (byte)10, (short)35, (byte)85),
    SWIFT("Swift", Type.NORMAL, MoveType.SPECIAL, (byte)20, (short)60, (byte)-1),
    SKULL_BASH("Skull Bash", Type.NORMAL, MoveType.PHYSICAL, (byte)15, (short)100, (byte)100),
    SPIKE_CANNON("Spike Cannon", Type.NORMAL, MoveType.PHYSICAL, (byte)15, (short)20, (byte)100),
    CONSTRICT("Constrict", Type.NORMAL, MoveType.PHYSICAL, (byte)35, (short)10, (byte)100),
    AMNESIA("Amnesia", Type.PSYCHIC, MoveType.STATUS, (byte)20, (short)-1, (byte)-1),
    KINESIS("Kinesis", Type.PSYCHIC, MoveType.STATUS, (byte)15, (short)-1, (byte)80),
    SOFTBOILED("Softboiled", Type.NORMAL, MoveType.STATUS, (byte)10, (short)-1, (byte)-1),
    HI_JUMP_KICK("Hi Jump Kick", Type.FIGHTING, MoveType.PHYSICAL, (byte)10, (short)130, (byte)90),
    GLARE("Glare", Type.NORMAL, MoveType.STATUS, (byte)30, (short)-1, (byte)90),
    DREAM_EATER("Dream Eater", Type.PSYCHIC, MoveType.SPECIAL, (byte)15, (short)100, (byte)100),
    POISON_GAS("Poison Gas", Type.POISON, MoveType.STATUS, (byte)40, (short)-1, (byte)80),
    BARRAGE("Barrage", Type.NORMAL, MoveType.PHYSICAL, (byte)20, (short)15, (byte)85),
    LEECH_LIFE("Leech Life", Type.BUG, MoveType.PHYSICAL, (byte)15, (short)20, (byte)100),
    LOVELY_KISS("Lovely Kiss", Type.NORMAL, MoveType.STATUS, (byte)10, (short)-1, (byte)75),
    SKY_ATTACK("Sky Attack", Type.FLYING, MoveType.PHYSICAL, (byte)5, (short)140, (byte)90),
    TRANSFORM("Transform", Type.NORMAL, MoveType.STATUS, (byte)10, (short)-1, (byte)-1),
    BUBBLE("Bubble", Type.WATER, MoveType.SPECIAL, (byte)30, (short)20, (byte)100),
    DIZZY_PUNCH("Dizzy Punch", Type.NORMAL, MoveType.PHYSICAL, (byte)10, (short)70, (byte)100),
    SPORE("Spore", Type.GRASS, MoveType.STATUS, (byte)15, (short)-1, (byte)100),
    FLASH("Flash", Type.NORMAL, MoveType.STATUS, (byte)20, (short)-1, (byte)100),
    PSYWAVE("Psywave", Type.PSYCHIC, MoveType.SPECIAL, (byte)15, (short)-1, (byte)80),
    SPLASH("Splash", Type.NORMAL, MoveType.STATUS, (byte)40, (short)-1, (byte)-1),
    ACID_ARMOR("Acid Armor", Type.POISON, MoveType.STATUS, (byte)40, (short)-1, (byte)-1),
    CRABHAMMER("Crabhammer", Type.WATER, MoveType.PHYSICAL, (byte)10, (short)90, (byte)90),
    EXPLOSION("Explosion", Type.NORMAL, MoveType.PHYSICAL, (byte)5, (short)250, (byte)100),
    FURY_SWIPES("Fury Swipes", Type.NORMAL, MoveType.PHYSICAL, (byte)15, (short)18, (byte)80),
    BONEMERANG("Bonemerang", Type.GROUND, MoveType.PHYSICAL, (byte)10, (short)50, (byte)90),
    REST("Rest", Type.PSYCHIC, MoveType.STATUS, (byte)10, (short)-1, (byte)-1),
    ROCK_SLIDE("Rock Slide", Type.ROCK, MoveType.PHYSICAL, (byte)10, (short)75, (byte)90),
    HYPER_FANG("Hyper Fang", Type.NORMAL, MoveType.PHYSICAL, (byte)15, (short)80, (byte)90),
    SHARPEN("Sharpen", Type.NORMAL, MoveType.STATUS, (byte)30, (short)-1, (byte)-1),
    CONVERSION("Conversion", Type.NORMAL, MoveType.STATUS, (byte)30, (short)-1, (byte)-1),
    TRI_ATTACK("Tri Attack", Type.NORMAL, MoveType.SPECIAL, (byte)10, (short)80, (byte)100),
    SUPER_FANG("Super Fang", Type.NORMAL, MoveType.PHYSICAL, (byte)10, (short)-1, (byte)90),
    SLASH("Slash", Type.NORMAL, MoveType.PHYSICAL, (byte)20, (short)70, (byte)100),
    SUBSTITUTE("Substitute", Type.NORMAL, MoveType.STATUS, (byte)10, (short)-1, (byte)-1),
    STRUGGLE("Struggle", Type.NORMAL, MoveType.PHYSICAL, (byte)1, (short)50, (byte)100),
    SKETCH("Sketch", Type.NORMAL, MoveType.STATUS, (byte)1, (short)-1, (byte)-1),
    TRIPLE_KICK("Triple Kick", Type.FIGHTING, MoveType.PHYSICAL, (byte)10, (short)10, (byte)90),
    THIEF("Thief", Type.DARK, MoveType.PHYSICAL, (byte)10, (short)40, (byte)100),
    SPIDER_WEB("Spider Web", Type.BUG, MoveType.STATUS, (byte)10, (short)-1, (byte)100),
    MIND_READER("Mind Reader", Type.NORMAL, MoveType.STATUS, (byte)5, (short)-1, (byte)100),
    NIGHTMARE("Nightmare", Type.GHOST, MoveType.STATUS, (byte)15, (short)-1, (byte)100),
    FLAME_WHEEL("Flame Wheel", Type.FIRE, MoveType.PHYSICAL, (byte)25, (short)60, (byte)100),
    SNORE("Snore", Type.NORMAL, MoveType.SPECIAL, (byte)15, (short)40, (byte)100),
    CURSE("Curse", Type.GHOST, MoveType.STATUS, (byte)10, (short)-1, (byte)-1),
    FLAIL("Flail", Type.NORMAL, MoveType.PHYSICAL, (byte)15, (short)-1, (byte)100),
    CONVERSION_2("Conversion 2", Type.NORMAL, MoveType.STATUS, (byte)30, (short)-1, (byte)100),
    AEROBLAST("Aeroblast", Type.FLYING, MoveType.SPECIAL, (byte)5, (short)100, (byte)95),
    COTTON_SPORE("Cotton Spore", Type.GRASS, MoveType.STATUS, (byte)40, (short)-1, (byte)100),
    REVERSAL("Reversal", Type.FIGHTING, MoveType.PHYSICAL, (byte)15, (short)-1, (byte)100),
    SPITE("Spite", Type.GHOST, MoveType.STATUS, (byte)10, (short)-1, (byte)100),
    POWDER_SNOW("Powder Snow", Type.ICE, MoveType.SPECIAL, (byte)25, (short)40, (byte)100),
    PROTECT("Protect", Type.NORMAL, MoveType.STATUS, (byte)10, (short)-1, (byte)-1),
    MACH_PUNCH("Mach Punch", Type.FIGHTING, MoveType.PHYSICAL, (byte)30, (short)40, (byte)100),
    SCARY_FACE("Scary Face", Type.NORMAL, MoveType.STATUS, (byte)10, (short)-1, (byte)100),
    FAINT_ATTACK("Faint Attack", Type.DARK, MoveType.PHYSICAL, (byte)20, (short)60, (byte)-1),
    SWEET_KISS("Sweet Kiss", Type.NORMAL, MoveType.STATUS, (byte)10, (short)-1, (byte)75),
    BELLY_DRUM("Belly Drum", Type.NORMAL, MoveType.STATUS, (byte)10, (short)-1, (byte)-1),
    SLUDGE_BOMB("Sludge Bomb", Type.POISON, MoveType.SPECIAL, (byte)10, (short)90, (byte)100),
    MUD_SLAP("Mud-Slap", Type.GROUND, MoveType.SPECIAL, (byte)10, (short)20, (byte)100),
    OCTAZOOKA("Octazooka", Type.WATER, MoveType.SPECIAL, (byte)10, (short)65, (byte)85),
    SPIKES("Spikes", Type.GROUND, MoveType.STATUS, (byte)20, (short)-1, (byte)-1),
    ZAP_CANNON("Zap Cannon", Type.ELECTRIC, MoveType.SPECIAL, (byte)5, (short)120, (byte)50),
    FORESIGHT("Foresight", Type.NORMAL, MoveType.STATUS, (byte)40, (short)-1, (byte)100),
    DESTINY_BOND("Destiny Bond", Type.GHOST, MoveType.STATUS, (byte)5, (short)-1, (byte)-1),
    PERISH_SONG("Perish Song", Type.NORMAL, MoveType.STATUS, (byte)5, (short)-1, (byte)-1),
    ICY_WIND("Icy Wind", Type.ICE, MoveType.SPECIAL, (byte)15, (short)55, (byte)95),
    DETECT("Detect", Type.FIGHTING, MoveType.STATUS, (byte)5, (short)-1, (byte)-1),
    BONE_RUSH("Bone Rush", Type.GROUND, MoveType.PHYSICAL, (byte)10, (short)25, (byte)90),
    LOCK_ON("Lock-On", Type.NORMAL, MoveType.STATUS, (byte)5, (short)-1, (byte)100),
    OUTRAGE("Outrage", Type.DRAGON, MoveType.PHYSICAL, (byte)15, (short)120, (byte)100),
    SANDSTORM("Sandstorm", Type.ROCK, MoveType.STATUS, (byte)10, (short)-1, (byte)-1),
    GIGA_DRAIN("Giga Drain", Type.GRASS, MoveType.SPECIAL, (byte)10, (short)75, (byte)100),
    ENDURE("Endure", Type.NORMAL, MoveType.STATUS, (byte)10, (short)-1, (byte)-1),
    CHARM("Charm", Type.NORMAL, MoveType.STATUS, (byte)20, (short)-1, (byte)100),
    ROLLOUT("Rollout", Type.ROCK, MoveType.PHYSICAL, (byte)20, (short)30, (byte)90),
    FALSE_SWIPE("False Swipe", Type.NORMAL, MoveType.PHYSICAL, (byte)40, (short)40, (byte)100),
    SWAGGER("Swagger", Type.NORMAL, MoveType.STATUS, (byte)15, (short)-1, (byte)90),
    MILK_DRINK("Milk Drink", Type.NORMAL, MoveType.STATUS, (byte)10, (short)-1, (byte)-1),
    SPARK("Spark", Type.ELECTRIC, MoveType.PHYSICAL, (byte)20, (short)65, (byte)100),
    FURY_CUTTER("Fury Cutter", Type.BUG, MoveType.PHYSICAL, (byte)20, (short)20, (byte)95),
    STEEL_WING("Steel Wing", Type.STEEL, MoveType.PHYSICAL, (byte)25, (short)70, (byte)90),
    MEAN_LOOK("Mean Look", Type.NORMAL, MoveType.STATUS, (byte)5, (short)-1, (byte)100),
    ATTRACT("Attract", Type.NORMAL, MoveType.STATUS, (byte)15, (short)-1, (byte)100),
    SLEEP_TALK("Sleep Talk", Type.NORMAL, MoveType.STATUS, (byte)10, (short)-1, (byte)-1),
    HEAL_BELL("Heal Bell", Type.NORMAL, MoveType.STATUS, (byte)5, (short)-1, (byte)-1),
    RETURN("Return", Type.NORMAL, MoveType.PHYSICAL, (byte)20, (short)-1, (byte)100),
    PRESENT("Present", Type.NORMAL, MoveType.PHYSICAL, (byte)15, (short)-1, (byte)90),
    FRUSTRATION("Frustration", Type.NORMAL, MoveType.PHYSICAL, (byte)20, (short)-1, (byte)100),
    SAFEGUARD("Safeguard", Type.NORMAL, MoveType.STATUS, (byte)25, (short)-1, (byte)-1),
    PAIN_SPLIT("Pain Split", Type.NORMAL, MoveType.STATUS, (byte)20, (short)-1, (byte)100),
    SACRED_FIRE("Sacred Fire", Type.FIRE, MoveType.PHYSICAL, (byte)5, (short)100, (byte)95),
    MAGNITUDE("Magnitude", Type.GROUND, MoveType.PHYSICAL, (byte)30, (short)-1, (byte)100),
    DYNAMICPUNCH("DynamicPunch", Type.FIGHTING, MoveType.PHYSICAL, (byte)5, (short)100, (byte)50),
    MEGAHORN("Megahorn", Type.BUG, MoveType.PHYSICAL, (byte)10, (short)120, (byte)85),
    DRAGONBREATH("DragonBreath", Type.DRAGON, MoveType.SPECIAL, (byte)20, (short)60, (byte)100),
    BATON_PASS("Baton Pass", Type.NORMAL, MoveType.STATUS, (byte)40, (short)-1, (byte)-1),
    ENCORE("Encore", Type.NORMAL, MoveType.STATUS, (byte)5, (short)-1, (byte)100),
    PURSUIT("Pursuit", Type.DARK, MoveType.PHYSICAL, (byte)20, (short)40, (byte)100),
    RAPID_SPIN("Rapid Spin", Type.NORMAL, MoveType.PHYSICAL, (byte)40, (short)20, (byte)100),
    SWEET_SCENT("Sweet Scent", Type.NORMAL, MoveType.STATUS, (byte)20, (short)-1, (byte)100),
    IRON_TAIL("Iron Tail", Type.STEEL, MoveType.PHYSICAL, (byte)15, (short)100, (byte)75),
    METAL_CLAW("Metal Claw", Type.STEEL, MoveType.PHYSICAL, (byte)35, (short)50, (byte)95),
    VITAL_THROW("Vital Throw", Type.FIGHTING, MoveType.PHYSICAL, (byte)10, (short)70, (byte)100),
    MORNING_SUN("Morning Sun", Type.NORMAL, MoveType.STATUS, (byte)5, (short)-1, (byte)-1),
    SYNTHESIS("Synthesis", Type.GRASS, MoveType.STATUS, (byte)5, (short)-1, (byte)-1),
    MOONLIGHT("Moonlight", Type.NORMAL, MoveType.STATUS, (byte)5, (short)-1, (byte)-1),
    HIDDEN_POWER("Hidden Power", Type.NORMAL, MoveType.SPECIAL, (byte)15, (short)-1, (byte)100),
    CROSS_CHOP("Cross Chop", Type.FIGHTING, MoveType.PHYSICAL, (byte)5, (short)100, (byte)80),
    TWISTER("Twister", Type.DRAGON, MoveType.SPECIAL, (byte)20, (short)40, (byte)100),
    RAIN_DANCE("Rain Dance", Type.WATER, MoveType.STATUS, (byte)5, (short)-1, (byte)-1),
    SUNNY_DAY("Sunny Day", Type.FIRE, MoveType.STATUS, (byte)5, (short)-1, (byte)-1),
    CRUNCH("Crunch", Type.DARK, MoveType.PHYSICAL, (byte)15, (short)80, (byte)100),
    MIRROR_COAT("Mirror Coat", Type.PSYCHIC, MoveType.SPECIAL, (byte)20, (short)-1, (byte)100),
    PSYCH_UP("Psych Up", Type.NORMAL, MoveType.STATUS, (byte)10, (short)-1, (byte)-1),
    EXTREMESPEED("ExtremeSpeed", Type.NORMAL, MoveType.PHYSICAL, (byte)5, (short)80, (byte)100),
    ANCIENTPOWER("AncientPower", Type.ROCK, MoveType.SPECIAL, (byte)5, (short)60, (byte)100),
    SHADOW_BALL("Shadow Ball", Type.GHOST, MoveType.SPECIAL, (byte)15, (short)80, (byte)100),
    FUTURE_SIGHT("Future Sight", Type.PSYCHIC, MoveType.SPECIAL, (byte)10, (short)100, (byte)100),
    ROCK_SMASH("Rock Smash", Type.FIGHTING, MoveType.PHYSICAL, (byte)15, (short)40, (byte)100),
    WHIRLPOOL("Whirlpool", Type.WATER, MoveType.SPECIAL, (byte)15, (short)35, (byte)85),
    BEAT_UP("Beat Up", Type.DARK, MoveType.PHYSICAL, (byte)10, (short)-1, (byte)100),
    FAKE_OUT("Fake Out", Type.NORMAL, MoveType.PHYSICAL, (byte)10, (short)40, (byte)100),
    UPROAR("Uproar", Type.NORMAL, MoveType.SPECIAL, (byte)10, (short)90, (byte)100),
    STOCKPILE("Stockpile", Type.NORMAL, MoveType.STATUS, (byte)20, (short)-1, (byte)-1),
    SPIT_UP("Spit Up", Type.NORMAL, MoveType.SPECIAL, (byte)10, (short)-1, (byte)100),
    SWALLOW("Swallow", Type.NORMAL, MoveType.STATUS, (byte)10, (short)-1, (byte)-1),
    HEAT_WAVE("Heat Wave", Type.FIRE, MoveType.SPECIAL, (byte)10, (short)100, (byte)90),
    HAIL("Hail", Type.ICE, MoveType.STATUS, (byte)10, (short)-1, (byte)-1),
    TORMENT("Torment", Type.DARK, MoveType.STATUS, (byte)15, (short)-1, (byte)100),
    FLATTER("Flatter", Type.DARK, MoveType.STATUS, (byte)15, (short)-1, (byte)100),
    WILL_O_WISP("Will-O-Wisp", Type.FIRE, MoveType.STATUS, (byte)15, (short)-1, (byte)75),
    MEMENTO("Memento", Type.DARK, MoveType.STATUS, (byte)10, (short)-1, (byte)100),
    FACADE("Facade", Type.NORMAL, MoveType.PHYSICAL, (byte)20, (short)70, (byte)100),
    FOCUS_PUNCH("Focus Punch", Type.FIGHTING, MoveType.PHYSICAL, (byte)20, (short)150, (byte)100),
    SMELLINGSALT("SmellingSalt", Type.NORMAL, MoveType.PHYSICAL, (byte)10, (short)60, (byte)100),
    FOLLOW_ME("Follow Me", Type.NORMAL, MoveType.STATUS, (byte)20, (short)-1, (byte)100),
    NATURE_POWER("Nature Power", Type.NORMAL, MoveType.STATUS, (byte)20, (short)-1, (byte)-1),
    CHARGE("Charge", Type.ELECTRIC, MoveType.STATUS, (byte)20, (short)-1, (byte)-1),
    TAUNT("Taunt", Type.DARK, MoveType.STATUS, (byte)20, (short)-1, (byte)100),
    HELPING_HAND("Helping Hand", Type.NORMAL, MoveType.STATUS, (byte)20, (short)-1, (byte)-1),
    TRICK("Trick", Type.PSYCHIC, MoveType.STATUS, (byte)10, (short)-1, (byte)100),
    ROLE_PLAY("Role Play", Type.PSYCHIC, MoveType.STATUS, (byte)10, (short)-1, (byte)-1),
    WISH("Wish", Type.NORMAL, MoveType.STATUS, (byte)10, (short)-1, (byte)-1),
    ASSIST("Assist", Type.NORMAL, MoveType.STATUS, (byte)20, (short)-1, (byte)-1),
    INGRAIN("Ingrain", Type.GRASS, MoveType.STATUS, (byte)20, (short)-1, (byte)-1),
    SUPERPOWER("Superpower", Type.FIGHTING, MoveType.PHYSICAL, (byte)5, (short)120, (byte)100),
    MAGIC_COAT("Magic Coat", Type.PSYCHIC, MoveType.STATUS, (byte)15, (short)-1, (byte)-1),
    RECYCLE("Recycle", Type.NORMAL, MoveType.STATUS, (byte)10, (short)-1, (byte)100),
    REVENGE("Revenge", Type.FIGHTING, MoveType.PHYSICAL, (byte)10, (short)60, (byte)100),
    BRICK_BREAK("Brick Break", Type.FIGHTING, MoveType.PHYSICAL, (byte)15, (short)75, (byte)100),
    YAWN("Yawn", Type.NORMAL, MoveType.STATUS, (byte)10, (short)-1, (byte)100),
    KNOCK_OFF("Knock Off", Type.DARK, MoveType.PHYSICAL, (byte)20, (short)20, (byte)100),
    ENDEAVOR("Endeavor", Type.NORMAL, MoveType.PHYSICAL, (byte)5, (short)-1, (byte)100),
    ERUPTION("Eruption", Type.FIRE, MoveType.SPECIAL, (byte)5, (short)-1, (byte)100),
    SKILL_SWAP("Skill Swap", Type.PSYCHIC, MoveType.STATUS, (byte)10, (short)-1, (byte)100),
    IMPRISON("Imprison", Type.PSYCHIC, MoveType.STATUS, (byte)10, (short)-1, (byte)100),
    REFRESH("Refresh", Type.NORMAL, MoveType.STATUS, (byte)20, (short)-1, (byte)100),
    GRUDGE("Grudge", Type.GHOST, MoveType.STATUS, (byte)5, (short)-1, (byte)100),
    SNATCH("Snatch", Type.DARK, MoveType.STATUS, (byte)10, (short)-1, (byte)100),
    SECRET_POWER("Secret Power", Type.NORMAL, MoveType.PHYSICAL, (byte)20, (short)70, (byte)100),
    DIVE("Dive", Type.WATER, MoveType.PHYSICAL, (byte)10, (short)80, (byte)100),
    ARM_THRUST("Arm Thrust", Type.FIGHTING, MoveType.PHYSICAL, (byte)20, (short)15, (byte)100),
    CAMOUFLAGE("Camouflage", Type.NORMAL, MoveType.STATUS, (byte)20, (short)-1, (byte)100),
    TAIL_GLOW("Tail Glow", Type.BUG, MoveType.STATUS, (byte)20, (short)-1, (byte)100),
    LUSTER_PURGE("Luster Purge", Type.PSYCHIC, MoveType.SPECIAL, (byte)5, (short)70, (byte)100),
    MIST_BALL("Mist Ball", Type.PSYCHIC, MoveType.SPECIAL, (byte)5, (short)70, (byte)100),
    FEATHERDANCE("FeatherDance", Type.FLYING, MoveType.STATUS, (byte)15, (short)-1, (byte)100),
    TEETER_DANCE("Teeter Dance", Type.NORMAL, MoveType.STATUS, (byte)20, (short)-1, (byte)100),
    BLAZE_KICK("Blaze Kick", Type.FIRE, MoveType.PHYSICAL, (byte)10, (short)85, (byte)90),
    MUD_SPORT("Mud Sport", Type.GROUND, MoveType.STATUS, (byte)15, (short)-1, (byte)100),
    ICE_BALL("Ice Ball", Type.ICE, MoveType.PHYSICAL, (byte)20, (short)30, (byte)90),
    NEEDLE_ARM("Needle Arm", Type.GRASS, MoveType.PHYSICAL, (byte)15, (short)60, (byte)100),
    SLACK_OFF("Slack Off", Type.NORMAL, MoveType.STATUS, (byte)10, (short)-1, (byte)100),
    HYPER_VOICE("Hyper Voice", Type.NORMAL, MoveType.SPECIAL, (byte)10, (short)90, (byte)100),
    POISON_FANG("Poison Fang", Type.POISON, MoveType.PHYSICAL, (byte)15, (short)50, (byte)100),
    CRUSH_CLAW("Crush Claw", Type.NORMAL, MoveType.PHYSICAL, (byte)10, (short)75, (byte)95),
    BLAST_BURN("Blast Burn", Type.FIRE, MoveType.SPECIAL, (byte)5, (short)150, (byte)90),
    HYDRO_CANNON("Hydro Cannon", Type.WATER, MoveType.SPECIAL, (byte)5, (short)150, (byte)90),
    METEOR_MASH("Meteor Mash", Type.STEEL, MoveType.PHYSICAL, (byte)10, (short)100, (byte)85),
    ASTONISH("Astonish", Type.GHOST, MoveType.PHYSICAL, (byte)15, (short)30, (byte)100),
    WEATHER_BALL("Weather Ball", Type.NORMAL, MoveType.SPECIAL, (byte)10, (short)50, (byte)100),
    AROMATHERAPY("Aromatherapy", Type.GRASS, MoveType.STATUS, (byte)5, (short)-1, (byte)-1),
    FAKE_TEARS("Fake Tears", Type.DARK, MoveType.STATUS, (byte)20, (short)-1, (byte)100),
    AIR_CUTTER("Air Cutter", Type.FLYING, MoveType.SPECIAL, (byte)25, (short)55, (byte)95),
    OVERHEAT("Overheat", Type.FIRE, MoveType.SPECIAL, (byte)5, (short)140, (byte)90),
    ODOR_SLEUTH("Odor Sleuth", Type.NORMAL, MoveType.STATUS, (byte)40, (short)-1, (byte)100),
    ROCK_TOMB("Rock Tomb", Type.ROCK, MoveType.PHYSICAL, (byte)10, (short)50, (byte)80),
    SILVER_WIND("Silver Wind", Type.BUG, MoveType.SPECIAL, (byte)5, (short)60, (byte)100),
    METAL_SOUND("Metal Sound", Type.STEEL, MoveType.STATUS, (byte)40, (short)-1, (byte)85),
    GRASSWHISTLE("GrassWhistle", Type.GRASS, MoveType.STATUS, (byte)15, (short)-1, (byte)55),
    TICKLE("Tickle", Type.NORMAL, MoveType.STATUS, (byte)20, (short)-1, (byte)100),
    COSMIC_POWER("Cosmic Power", Type.PSYCHIC, MoveType.STATUS, (byte)20, (short)-1, (byte)-1),
    WATER_SPOUT("Water Spout", Type.WATER, MoveType.SPECIAL, (byte)5, (short)-1, (byte)100),
    SIGNAL_BEAM("Signal Beam", Type.BUG, MoveType.SPECIAL, (byte)15, (short)75, (byte)100),
    SHADOW_PUNCH("Shadow Punch", Type.GHOST, MoveType.PHYSICAL, (byte)20, (short)60, (byte)-1),
    EXTRASENSORY("Extrasensory", Type.PSYCHIC, MoveType.SPECIAL, (byte)30, (short)80, (byte)100),
    SKY_UPPERCUT("Sky Uppercut", Type.FIGHTING, MoveType.PHYSICAL, (byte)15, (short)85, (byte)90),
    SAND_TOMB("Sand Tomb", Type.GROUND, MoveType.PHYSICAL, (byte)15, (short)35, (byte)85),
    SHEER_COLD("Sheer Cold", Type.ICE, MoveType.SPECIAL, (byte)5, (short)-1, (byte)-1),
    MUDDY_WATER("Muddy Water", Type.WATER, MoveType.SPECIAL, (byte)10, (short)95, (byte)85),
    BULLET_SEED("Bullet Seed", Type.GRASS, MoveType.PHYSICAL, (byte)30, (short)25, (byte)100),
    AERIAL_ACE("Aerial Ace", Type.FLYING, MoveType.PHYSICAL, (byte)20, (short)60, (byte)-1),
    ICICLE_SPEAR("Icicle Spear", Type.ICE, MoveType.PHYSICAL, (byte)30, (short)25, (byte)100),
    IRON_DEFENSE("Iron Defense", Type.STEEL, MoveType.STATUS, (byte)15, (short)-1, (byte)-1),
    BLOCK("Block", Type.NORMAL, MoveType.STATUS, (byte)5, (short)-1, (byte)100),
    HOWL("Howl", Type.NORMAL, MoveType.STATUS, (byte)40, (short)-1, (byte)-1),
    DRAGON_CLAW("Dragon Claw", Type.DRAGON, MoveType.PHYSICAL, (byte)15, (short)80, (byte)100),
    FRENZY_PLANT("Frenzy Plant", Type.GRASS, MoveType.SPECIAL, (byte)5, (short)150, (byte)90),
    BULK_UP("Bulk Up", Type.FIGHTING, MoveType.STATUS, (byte)20, (short)-1, (byte)-1),
    BOUNCE("Bounce", Type.FLYING, MoveType.PHYSICAL, (byte)5, (short)85, (byte)85),
    MUD_SHOT("Mud Shot", Type.GROUND, MoveType.SPECIAL, (byte)15, (short)55, (byte)95),
    POISON_TAIL("Poison Tail", Type.POISON, MoveType.PHYSICAL, (byte)25, (short)50, (byte)100),
    COVET("Covet", Type.NORMAL, MoveType.PHYSICAL, (byte)40, (short)60, (byte)100),
    VOLT_TACKLE("Volt Tackle", Type.ELECTRIC, MoveType.PHYSICAL, (byte)15, (short)120, (byte)100),
    MAGICAL_LEAF("Magical Leaf", Type.GRASS, MoveType.SPECIAL, (byte)20, (short)60, (byte)-1),
    WATER_SPORT("Water Sport", Type.WATER, MoveType.STATUS, (byte)15, (short)-1, (byte)100),
    CALM_MIND("Calm Mind", Type.PSYCHIC, MoveType.STATUS, (byte)20, (short)-1, (byte)-1),
    LEAF_BLADE("Leaf Blade", Type.GRASS, MoveType.PHYSICAL, (byte)15, (short)90, (byte)100),
    DRAGON_DANCE("Dragon Dance", Type.DRAGON, MoveType.STATUS, (byte)20, (short)-1, (byte)-1),
    ROCK_BLAST("Rock Blast", Type.ROCK, MoveType.PHYSICAL, (byte)10, (short)25, (byte)90),
    SHOCK_WAVE("Shock Wave", Type.ELECTRIC, MoveType.SPECIAL, (byte)20, (short)60, (byte)-1),
    WATER_PULSE("Water Pulse", Type.WATER, MoveType.SPECIAL, (byte)20, (short)60, (byte)100),
    DOOM_DESIRE("Doom Desire", Type.STEEL, MoveType.SPECIAL, (byte)5, (short)140, (byte)100),
    PSYCHO_BOOST("Psycho Boost", Type.PSYCHIC, MoveType.SPECIAL, (byte)5, (short)140, (byte)90),
    ROOST("Roost", Type.FLYING, MoveType.STATUS, (byte)10, (short)-1, (byte)-1),
    GRAVITY("Gravity", Type.PSYCHIC, MoveType.STATUS, (byte)5, (short)-1, (byte)-1),
    MIRACLE_EYE("Miracle Eye", Type.PSYCHIC, MoveType.STATUS, (byte)40, (short)-1, (byte)-1),
    WAKE_UP_SLAP("Wake-Up Slap", Type.FIGHTING, MoveType.PHYSICAL, (byte)10, (short)60, (byte)100),
    HAMMER_ARM("Hammer Arm", Type.FIGHTING, MoveType.PHYSICAL, (byte)10, (short)100, (byte)90),
    GYRO_BALL("Gyro Ball", Type.STEEL, MoveType.PHYSICAL, (byte)5, (short)-1, (byte)100),
    HEALING_WISH("Healing Wish", Type.PSYCHIC, MoveType.STATUS, (byte)10, (short)-1, (byte)-1),
    BRINE("Brine", Type.WATER, MoveType.SPECIAL, (byte)10, (short)65, (byte)100),
    NATURAL_GIFT("Natural Gift", Type.NORMAL, MoveType.PHYSICAL, (byte)15, (short)-1, (byte)100),
    FEINT("Feint", Type.NORMAL, MoveType.PHYSICAL, (byte)10, (short)30, (byte)100),
    PLUCK("Pluck", Type.FLYING, MoveType.PHYSICAL, (byte)20, (short)60, (byte)100),
    TAILWIND("Tailwind", Type.FLYING, MoveType.STATUS, (byte)30, (short)-1, (byte)-1),
    ACUPRESSURE("Acupressure", Type.NORMAL, MoveType.STATUS, (byte)30, (short)-1, (byte)-1),
    METAL_BURST("Metal Burst", Type.STEEL, MoveType.PHYSICAL, (byte)10, (short)-1, (byte)100),
    U_TURN("U-turn", Type.BUG, MoveType.PHYSICAL, (byte)20, (short)70, (byte)100),
    CLOSE_COMBAT("Close Combat", Type.FIGHTING, MoveType.PHYSICAL, (byte)5, (short)120, (byte)100),
    PAYBACK("Payback", Type.DARK, MoveType.PHYSICAL, (byte)10, (short)50, (byte)100),
    ASSURANCE("Assurance", Type.DARK, MoveType.PHYSICAL, (byte)10, (short)50, (byte)100),
    EMBARGO("Embargo", Type.DARK, MoveType.STATUS, (byte)15, (short)-1, (byte)100),
    FLING("Fling", Type.DARK, MoveType.PHYSICAL, (byte)10, (short)-1, (byte)100),
    PSYCHO_SHIFT("Psycho Shift", Type.PSYCHIC, MoveType.STATUS, (byte)10, (short)-1, (byte)90),
    TRUMP_CARD("Trump Card", Type.NORMAL, MoveType.SPECIAL, (byte)5, (short)-1, (byte)-1),
    HEAL_BLOCK("Heal Block", Type.PSYCHIC, MoveType.STATUS, (byte)15, (short)-1, (byte)100),
    WRING_OUT("Wring Out", Type.NORMAL, MoveType.SPECIAL, (byte)5, (short)-1, (byte)100),
    POWER_TRICK("Power Trick", Type.PSYCHIC, MoveType.STATUS, (byte)10, (short)-1, (byte)-1),
    GASTRO_ACID("Gastro Acid", Type.POISON, MoveType.STATUS, (byte)10, (short)-1, (byte)100),
    LUCKY_CHANT("Lucky Chant", Type.NORMAL, MoveType.STATUS, (byte)30, (short)-1, (byte)-1),
    ME_FIRST("Me First", Type.NORMAL, MoveType.STATUS, (byte)20, (short)-1, (byte)-1),
    COPYCAT("Copycat", Type.NORMAL, MoveType.STATUS, (byte)20, (short)-1, (byte)-1),
    POWER_SWAP("Power Swap", Type.PSYCHIC, MoveType.STATUS, (byte)10, (short)-1, (byte)-1),
    GUARD_SWAP("Guard Swap", Type.PSYCHIC, MoveType.STATUS, (byte)10, (short)-1, (byte)-1),
    PUNISHMENT("Punishment", Type.DARK, MoveType.PHYSICAL, (byte)5, (short)-1, (byte)100),
    LAST_RESORT("Last Resort", Type.NORMAL, MoveType.PHYSICAL, (byte)5, (short)140, (byte)100),
    WORRY_SEED("Worry Seed", Type.GRASS, MoveType.STATUS, (byte)10, (short)-1, (byte)100),
    SUCKER_PUNCH("Sucker Punch", Type.DARK, MoveType.PHYSICAL, (byte)5, (short)80, (byte)100),
    TOXIC_SPIKES("Toxic Spikes", Type.POISON, MoveType.STATUS, (byte)20, (short)-1, (byte)-1),
    HEART_SWAP("Heart Swap", Type.PSYCHIC, MoveType.STATUS, (byte)10, (short)-1, (byte)-1),
    AQUA_RING("Aqua Ring", Type.WATER, MoveType.STATUS, (byte)20, (short)-1, (byte)-1),
    MAGNET_RISE("Magnet Rise", Type.ELECTRIC, MoveType.STATUS, (byte)10, (short)-1, (byte)-1),
    FLARE_BLITZ("Flare Blitz", Type.FIRE, MoveType.PHYSICAL, (byte)15, (short)120, (byte)100),
    FORCE_PALM("Force Palm", Type.FIGHTING, MoveType.PHYSICAL, (byte)10, (short)60, (byte)100),
    AURA_SPHERE("Aura Sphere", Type.FIGHTING, MoveType.SPECIAL, (byte)20, (short)90, (byte)-1),
    ROCK_POLISH("Rock Polish", Type.ROCK, MoveType.STATUS, (byte)20, (short)-1, (byte)-1),
    POISON_JAB("Poison Jab", Type.POISON, MoveType.PHYSICAL, (byte)20, (short)80, (byte)100),
    DARK_PULSE("Dark Pulse", Type.DARK, MoveType.SPECIAL, (byte)15, (short)80, (byte)100),
    NIGHT_SLASH("Night Slash", Type.DARK, MoveType.PHYSICAL, (byte)15, (short)70, (byte)100),
    AQUA_TAIL("Aqua Tail", Type.WATER, MoveType.PHYSICAL, (byte)10, (short)90, (byte)90),
    SEED_BOMB("Seed Bomb", Type.GRASS, MoveType.PHYSICAL, (byte)15, (short)80, (byte)100),
    AIR_SLASH("Air Slash", Type.FLYING, MoveType.SPECIAL, (byte)20, (short)75, (byte)95),
    X_SCISSOR("X-Scissor", Type.BUG, MoveType.PHYSICAL, (byte)15, (short)80, (byte)100),
    BUG_BUZZ("Bug Buzz", Type.BUG, MoveType.SPECIAL, (byte)10, (short)90, (byte)100),
    DRAGON_PULSE("Dragon Pulse", Type.DRAGON, MoveType.SPECIAL, (byte)10, (short)90, (byte)100),
    DRAGON_RUSH("Dragon Rush", Type.DRAGON, MoveType.PHYSICAL, (byte)10, (short)100, (byte)75),
    POWER_GEM("Power Gem", Type.ROCK, MoveType.SPECIAL, (byte)20, (short)70, (byte)100),
    DRAIN_PUNCH("Drain Punch", Type.FIGHTING, MoveType.PHYSICAL, (byte)10, (short)75, (byte)100),
    VACUUM_WAVE("Vacuum Wave", Type.FIGHTING, MoveType.SPECIAL, (byte)30, (short)40, (byte)100),
    FOCUS_BLAST("Focus Blast", Type.FIGHTING, MoveType.SPECIAL, (byte)5, (short)120, (byte)70),
    ENERGY_BALL("Energy Ball", Type.GRASS, MoveType.SPECIAL, (byte)10, (short)80, (byte)100),
    BRAVE_BIRD("Brave Bird", Type.FLYING, MoveType.PHYSICAL, (byte)15, (short)120, (byte)100),
    EARTH_POWER("Earth Power", Type.GROUND, MoveType.SPECIAL, (byte)10, (short)90, (byte)100),
    SWITCHEROO("Switcheroo", Type.DARK, MoveType.STATUS, (byte)10, (short)-1, (byte)100),
    GIGA_IMPACT("Giga Impact", Type.NORMAL, MoveType.PHYSICAL, (byte)5, (short)150, (byte)90),
    NASTY_PLOT("Nasty Plot", Type.DARK, MoveType.STATUS, (byte)20, (short)-1, (byte)-1),
    BULLET_PUNCH("Bullet Punch", Type.STEEL, MoveType.PHYSICAL, (byte)30, (short)40, (byte)100),
    AVALANCHE("Avalanche", Type.ICE, MoveType.PHYSICAL, (byte)10, (short)60, (byte)100),
    ICE_SHARD("Ice Shard", Type.ICE, MoveType.PHYSICAL, (byte)30, (short)40, (byte)100),
    SHADOW_CLAW("Shadow Claw", Type.GHOST, MoveType.PHYSICAL, (byte)15, (short)70, (byte)100),
    THUNDER_FANG("Thunder Fang", Type.ELECTRIC, MoveType.PHYSICAL, (byte)15, (short)65, (byte)95),
    ICE_FANG("Ice Fang", Type.ICE, MoveType.PHYSICAL, (byte)15, (short)65, (byte)95),
    FIRE_FANG("Fire Fang", Type.FIRE, MoveType.PHYSICAL, (byte)15, (short)65, (byte)95),
    SHADOW_SNEAK("Shadow Sneak", Type.GHOST, MoveType.PHYSICAL, (byte)30, (short)40, (byte)100),
    MUD_BOMB("Mud Bomb", Type.GROUND, MoveType.SPECIAL, (byte)10, (short)65, (byte)85),
    PSYCHO_CUT("Psycho Cut", Type.PSYCHIC, MoveType.PHYSICAL, (byte)20, (short)70, (byte)100),
    ZEN_HEADBUTT("Zen Headbutt", Type.PSYCHIC, MoveType.PHYSICAL, (byte)15, (short)80, (byte)90),
    MIRROR_SHOT("Mirror Shot", Type.STEEL, MoveType.SPECIAL, (byte)10, (short)65, (byte)85),
    FLASH_CANNON("Flash Cannon", Type.STEEL, MoveType.SPECIAL, (byte)10, (short)80, (byte)100),
    ROCK_CLIMB("Rock Climb", Type.NORMAL, MoveType.PHYSICAL, (byte)20, (short)90, (byte)85),
    DEFOG("Defog", Type.FLYING, MoveType.STATUS, (byte)15, (short)-1, (byte)-1),
    TRICK_ROOM("Trick Room", Type.PSYCHIC, MoveType.STATUS, (byte)5, (short)-1, (byte)-1),
    DRACO_METEOR("Draco Meteor", Type.DRAGON, MoveType.SPECIAL, (byte)5, (short)140, (byte)90),
    DISCHARGE("Discharge", Type.ELECTRIC, MoveType.SPECIAL, (byte)15, (short)80, (byte)100),
    LAVA_PLUME("Lava Plume", Type.FIRE, MoveType.SPECIAL, (byte)15, (short)80, (byte)100),
    LEAF_STORM("Leaf Storm", Type.GRASS, MoveType.SPECIAL, (byte)5, (short)140, (byte)90),
    POWER_WHIP("Power Whip", Type.GRASS, MoveType.PHYSICAL, (byte)10, (short)120, (byte)85),
    ROCK_WRECKER("Rock Wrecker", Type.ROCK, MoveType.PHYSICAL, (byte)5, (short)150, (byte)90),
    CROSS_POISON("Cross Poison", Type.POISON, MoveType.PHYSICAL, (byte)20, (short)70, (byte)100),
    GUNK_SHOT("Gunk Shot", Type.POISON, MoveType.PHYSICAL, (byte)5, (short)120, (byte)70),
    IRON_HEAD("Iron Head", Type.STEEL, MoveType.PHYSICAL, (byte)15, (short)80, (byte)100),
    MAGNET_BOMB("Magnet Bomb", Type.STEEL, MoveType.PHYSICAL, (byte)20, (short)60, (byte)-1),
    STONE_EDGE("Stone Edge", Type.ROCK, MoveType.PHYSICAL, (byte)5, (short)100, (byte)80),
    CAPTIVATE("Captivate", Type.NORMAL, MoveType.STATUS, (byte)20, (short)-1, (byte)100),
    STEALTH_ROCK("Stealth Rock", Type.ROCK, MoveType.STATUS, (byte)20, (short)-1, (byte)-1),
    GRASS_KNOT("Grass Knot", Type.GRASS, MoveType.SPECIAL, (byte)20, (short)-1, (byte)100),
    CHATTER("Chatter", Type.FLYING, MoveType.SPECIAL, (byte)20, (short)60, (byte)100),
    JUDGMENT("Judgment", Type.NORMAL, MoveType.SPECIAL, (byte)10, (short)100, (byte)100),
    BUG_BITE("Bug Bite", Type.BUG, MoveType.PHYSICAL, (byte)20, (short)60, (byte)100),
    CHARGE_BEAM("Charge Beam", Type.ELECTRIC, MoveType.SPECIAL, (byte)10, (short)50, (byte)90),
    WOOD_HAMMER("Wood Hammer", Type.GRASS, MoveType.PHYSICAL, (byte)15, (short)120, (byte)100),
    AQUA_JET("Aqua Jet", Type.WATER, MoveType.PHYSICAL, (byte)20, (short)40, (byte)100),
    ATTACK_ORDER("Attack Order", Type.BUG, MoveType.PHYSICAL, (byte)15, (short)90, (byte)100),
    DEFEND_ORDER("Defend Order", Type.BUG, MoveType.STATUS, (byte)10, (short)-1, (byte)-1),
    HEAL_ORDER("Heal Order", Type.BUG, MoveType.STATUS, (byte)10, (short)-1, (byte)-1),
    HEAD_SMASH("Head Smash", Type.ROCK, MoveType.PHYSICAL, (byte)5, (short)150, (byte)80),
    DOUBLE_HIT("Double Hit", Type.NORMAL, MoveType.PHYSICAL, (byte)10, (short)35, (byte)90),
    ROAR_OF_TIME("Roar of Time", Type.DRAGON, MoveType.SPECIAL, (byte)5, (short)150, (byte)90),
    SPACIAL_REND("Spacial Rend", Type.DRAGON, MoveType.SPECIAL, (byte)5, (short)100, (byte)95),
    LUNAR_DANCE("Lunar Dance", Type.PSYCHIC, MoveType.STATUS, (byte)10, (short)-1, (byte)-1),
    CRUSH_GRIP("Crush Grip", Type.NORMAL, MoveType.PHYSICAL, (byte)5, (short)-1, (byte)100),
    MAGMA_STORM("Magma Storm", Type.FIRE, MoveType.SPECIAL, (byte)5, (short)120, (byte)75),
    DARK_VOID("Dark Void", Type.DARK, MoveType.STATUS, (byte)10, (short)-1, (byte)80),
    SEED_FLARE("Seed Flare", Type.GRASS, MoveType.SPECIAL, (byte)5, (short)120, (byte)85),
    OMINOUS_WIND("Ominous Wind", Type.GHOST, MoveType.SPECIAL, (byte)5, (short)60, (byte)100),
    SHADOW_FORCE("Shadow Force", Type.GHOST, MoveType.PHYSICAL, (byte)5, (short)120, (byte)100),
    HONE_CLAWS("Hone Claws", Type.DARK, MoveType.STATUS, (byte)15, (short)-1, (byte)-1),
    WIDE_GUARD("Wide Guard", Type.ROCK, MoveType.STATUS, (byte)10, (short)-1, (byte)-1),
    GUARD_SPLIT("Guard Split", Type.PSYCHIC, MoveType.STATUS, (byte)10, (short)-1, (byte)-1),
    POWER_SPLIT("Power Split", Type.PSYCHIC, MoveType.STATUS, (byte)10, (short)-1, (byte)-1),
    WONDER_ROOM("Wonder Room", Type.PSYCHIC, MoveType.STATUS, (byte)10, (short)-1, (byte)-1),
    PSYSHOCK("Psyshock", Type.PSYCHIC, MoveType.SPECIAL, (byte)10, (short)80, (byte)100),
    VENOSHOCK("Venoshock", Type.POISON, MoveType.SPECIAL, (byte)10, (short)65, (byte)100),
    AUTOTOMIZE("Autotomize", Type.STEEL, MoveType.STATUS, (byte)15, (short)-1, (byte)-1),
    RAGE_POWDER("Rage Powder", Type.BUG, MoveType.STATUS, (byte)20, (short)-1, (byte)-1),
    TELEKINESIS("Telekinesis", Type.PSYCHIC, MoveType.STATUS, (byte)15, (short)-1, (byte)-1),
    MAGIC_ROOM("Magic Room", Type.PSYCHIC, MoveType.STATUS, (byte)10, (short)-1, (byte)-1),
    SMACK_DOWN("Smack Down", Type.ROCK, MoveType.PHYSICAL, (byte)15, (short)50, (byte)100),
    STORM_THROW("Storm Throw", Type.FIGHTING, MoveType.PHYSICAL, (byte)10, (short)40, (byte)100),
    FLAME_BURST("Flame Burst", Type.FIRE, MoveType.SPECIAL, (byte)15, (short)70, (byte)100),
    SLUDGE_WAVE("Sludge Wave", Type.POISON, MoveType.SPECIAL, (byte)10, (short)95, (byte)100),
    QUIVER_DANCE("Quiver Dance", Type.BUG, MoveType.STATUS, (byte)20, (short)-1, (byte)-1),
    HEAVY_SLAM("Heavy Slam", Type.STEEL, MoveType.PHYSICAL, (byte)10, (short)-1, (byte)100),
    SYNCHRONOISE("Synchronoise", Type.PSYCHIC, MoveType.SPECIAL, (byte)15, (short)70, (byte)100),
    ELECTRO_BALL("Electro Ball", Type.ELECTRIC, MoveType.SPECIAL, (byte)10, (short)-1, (byte)100),
    SOAK("Soak", Type.WATER, MoveType.STATUS, (byte)20, (short)-1, (byte)100),
    FLAME_CHARGE("Flame Charge", Type.FIRE, MoveType.PHYSICAL, (byte)20, (short)50, (byte)100),
    COIL("Coil", Type.POISON, MoveType.STATUS, (byte)20, (short)-1, (byte)-1),
    LOW_SWEEP("Low Sweep", Type.FIGHTING, MoveType.PHYSICAL, (byte)20, (short)60, (byte)100),
    ACID_SPRAY("Acid Spray", Type.POISON, MoveType.SPECIAL, (byte)20, (short)40, (byte)100),
    FOUL_PLAY("Foul Play", Type.DARK, MoveType.PHYSICAL, (byte)15, (short)95, (byte)100),
    SIMPLE_BEAM("Simple Beam", Type.NORMAL, MoveType.STATUS, (byte)15, (short)-1, (byte)100),
    ENTRAINMENT("Entrainment", Type.NORMAL, MoveType.STATUS, (byte)15, (short)-1, (byte)100),
    AFTER_YOU("After You", Type.NORMAL, MoveType.STATUS, (byte)15, (short)-1, (byte)-1),
    ROUND("Round", Type.NORMAL, MoveType.SPECIAL, (byte)15, (short)60, (byte)100),
    ECHOED_VOICE("Echoed Voice", Type.NORMAL, MoveType.SPECIAL, (byte)15, (short)40, (byte)100),
    CHIP_AWAY("Chip Away", Type.NORMAL, MoveType.PHYSICAL, (byte)20, (short)70, (byte)100),
    CLEAR_SMOG("Clear Smog", Type.POISON, MoveType.SPECIAL, (byte)15, (short)50, (byte)-1),
    STORED_POWER("Stored Power", Type.PSYCHIC, MoveType.SPECIAL, (byte)10, (short)20, (byte)100),
    QUICK_GUARD("Quick Guard", Type.FIGHTING, MoveType.STATUS, (byte)15, (short)-1, (byte)-1),
    ALLY_SWITCH("Ally Switch", Type.PSYCHIC, MoveType.STATUS, (byte)15, (short)-1, (byte)-1),
    SCALD("Scald", Type.WATER, MoveType.SPECIAL, (byte)15, (short)80, (byte)100),
    SHELL_SMASH("Shell Smash", Type.NORMAL, MoveType.STATUS, (byte)15, (short)-1, (byte)-1),
    HEAL_PULSE("Heal Pulse", Type.PSYCHIC, MoveType.STATUS, (byte)10, (short)-1, (byte)-1),
    HEX("Hex", Type.GHOST, MoveType.SPECIAL, (byte)10, (short)50, (byte)100),
    SKY_DROP("Sky Drop", Type.FLYING, MoveType.PHYSICAL, (byte)10, (short)60, (byte)100),
    SHIFT_GEAR("Shift Gear", Type.STEEL, MoveType.STATUS, (byte)10, (short)-1, (byte)-1),
    CIRCLE_THROW("Circle Throw", Type.FIGHTING, MoveType.PHYSICAL, (byte)10, (short)60, (byte)90),
    INCINERATE("Incinerate", Type.FIRE, MoveType.SPECIAL, (byte)15, (short)30, (byte)100),
    QUASH("Quash", Type.DARK, MoveType.STATUS, (byte)15, (short)-1, (byte)100),
    ACROBATICS("Acrobatics", Type.FLYING, MoveType.PHYSICAL, (byte)15, (short)55, (byte)100),
    REFLECT_TYPE("Reflect Type", Type.NORMAL, MoveType.STATUS, (byte)15, (short)-1, (byte)-1),
    RETALIATE("Retaliate", Type.NORMAL, MoveType.PHYSICAL, (byte)5, (short)70, (byte)100),
    FINAL_GAMBIT("Final Gambit", Type.FIGHTING, MoveType.SPECIAL, (byte)5, (short)-1, (byte)100),
    BESTOW("Bestow", Type.NORMAL, MoveType.STATUS, (byte)15, (short)-1, (byte)-1),
    INFERNO("Inferno", Type.FIRE, MoveType.SPECIAL, (byte)5, (short)100, (byte)50),
    WATER_PLEDGE("Water Pledge", Type.WATER, MoveType.SPECIAL, (byte)10, (short)50, (byte)100),
    FIRE_PLEDGE("Fire Pledge", Type.FIRE, MoveType.SPECIAL, (byte)10, (short)50, (byte)100),
    GRASS_PLEDGE("Grass Pledge", Type.GRASS, MoveType.SPECIAL, (byte)10, (short)50, (byte)100),
    VOLT_SWITCH("Volt Switch", Type.ELECTRIC, MoveType.SPECIAL, (byte)20, (short)70, (byte)100),
    STRUGGLE_BUG("Struggle Bug", Type.BUG, MoveType.SPECIAL, (byte)20, (short)30, (byte)100),
    BULLDOZE("Bulldoze", Type.GROUND, MoveType.PHYSICAL, (byte)20, (short)60, (byte)100),
    FROST_BREATH("Frost Breath", Type.ICE, MoveType.SPECIAL, (byte)10, (short)40, (byte)90),
    DRAGON_TAIL("Dragon Tail", Type.DRAGON, MoveType.PHYSICAL, (byte)10, (short)60, (byte)90),
    WORK_UP("Work Up", Type.NORMAL, MoveType.STATUS, (byte)30, (short)-1, (byte)-1),
    ELECTROWEB("Electroweb", Type.ELECTRIC, MoveType.SPECIAL, (byte)15, (short)55, (byte)95),
    WILD_CHARGE("Wild Charge", Type.ELECTRIC, MoveType.PHYSICAL, (byte)15, (short)90, (byte)100),
    DRILL_RUN("Drill Run", Type.GROUND, MoveType.PHYSICAL, (byte)10, (short)80, (byte)95),
    DUAL_CHOP("Dual Chop", Type.DRAGON, MoveType.PHYSICAL, (byte)15, (short)40, (byte)90),
    HEART_STAMP("Heart Stamp", Type.PSYCHIC, MoveType.PHYSICAL, (byte)25, (short)60, (byte)100),
    HORN_LEECH("Horn Leech", Type.GRASS, MoveType.PHYSICAL, (byte)10, (short)75, (byte)100),
    SACRED_SWORD("Sacred Sword", Type.FIGHTING, MoveType.PHYSICAL, (byte)20, (short)90, (byte)100),
    RAZOR_SHELL("Razor Shell", Type.WATER, MoveType.PHYSICAL, (byte)10, (short)75, (byte)95),
    HEAT_CRASH("Heat Crash", Type.FIRE, MoveType.PHYSICAL, (byte)10, (short)-1, (byte)100),
    LEAF_TORNADO("Leaf Tornado", Type.GRASS, MoveType.SPECIAL, (byte)10, (short)65, (byte)90),
    STEAMROLLER("Steamroller", Type.BUG, MoveType.PHYSICAL, (byte)20, (short)65, (byte)100),
    COTTON_GUARD("Cotton Guard", Type.GRASS, MoveType.STATUS, (byte)10, (short)-1, (byte)-1),
    NIGHT_DAZE("Night Daze", Type.DARK, MoveType.SPECIAL, (byte)10, (short)85, (byte)95),
    PSYSTRIKE("Psystrike", Type.PSYCHIC, MoveType.SPECIAL, (byte)10, (short)100, (byte)100),
    TAIL_SLAP("Tail Slap", Type.NORMAL, MoveType.PHYSICAL, (byte)10, (short)25, (byte)85),
    HURRICANE("Hurricane", Type.FLYING, MoveType.SPECIAL, (byte)10, (short)120, (byte)70),
    HEAD_CHARGE("Head Charge", Type.NORMAL, MoveType.PHYSICAL, (byte)15, (short)120, (byte)100),
    GEAR_GRIND("Gear Grind", Type.STEEL, MoveType.PHYSICAL, (byte)15, (short)50, (byte)85),
    SEARING_SHOT("Searing Shot", Type.FIRE, MoveType.SPECIAL, (byte)5, (short)100, (byte)100),
    TECHNO_BLAST("Techno Blast", Type.NORMAL, MoveType.SPECIAL, (byte)5, (short)85, (byte)100),
    RELIC_SONG("Relic Song", Type.NORMAL, MoveType.SPECIAL, (byte)10, (short)75, (byte)100),
    SECRET_SWORD("Secret Sword", Type.FIGHTING, MoveType.SPECIAL, (byte)10, (short)85, (byte)100),
    GLACIATE("Glaciate", Type.ICE, MoveType.SPECIAL, (byte)10, (short)65, (byte)95),
    BOLT_STRIKE("Bolt Strike", Type.ELECTRIC, MoveType.PHYSICAL, (byte)5, (short)130, (byte)85),
    BLUE_FLARE("Blue Flare", Type.FIRE, MoveType.SPECIAL, (byte)5, (short)130, (byte)85),
    FIERY_DANCE("Fiery Dance", Type.FIRE, MoveType.SPECIAL, (byte)10, (short)80, (byte)100),
    FREEZE_SHOCK("Freeze Shock", Type.ICE, MoveType.PHYSICAL, (byte)5, (short)140, (byte)90),
    ICE_BURN("Ice Burn", Type.ICE, MoveType.SPECIAL, (byte)5, (short)140, (byte)90),
    SNARL("Snarl", Type.DARK, MoveType.SPECIAL, (byte)15, (short)55, (byte)95),
    ICICLE_CRASH("Icicle Crash", Type.ICE, MoveType.PHYSICAL, (byte)10, (short)85, (byte)90),
    V_CREATE("V-create", Type.FIRE, MoveType.PHYSICAL, (byte)5, (short)180, (byte)95),
    FUSION_FLARE("Fusion Flare", Type.FIRE, MoveType.SPECIAL, (byte)5, (short)100, (byte)100),
    FUSION_BOLT("Fusion Bolt", Type.ELECTRIC, MoveType.PHYSICAL, (byte)5, (short)100, (byte)100);
    
    private final String NAME;
    private final Type TYPE;
    private final short POWER;
    private final byte ACCURACY;
    private final MoveType MOVE_TYPE;
    private final Status SIDE_EFFECT;
    private final Stat STAT_LOWERED;
    private byte pp, battlePP, battleAccuracy;

    Move(String name, Type type, MoveType m, byte pp, short power, byte accuracy)
    {
        NAME = name;
        TYPE = type;
        ACCURACY = accuracy;
        MOVE_TYPE = m;
        POWER = power;
        this.pp = pp;
        battlePP = pp;
        SIDE_EFFECT = null;
        STAT_LOWERED = null;
    }

    /*Move(String name, Type type, MoveType m, int power, int pp, int accuracy, Status s)
    {
        NAME = name;
        TYPE = type;
        ACCURACY = accuracy;
        POWER = power;
        this.pp = pp;
        battlePP = pp;
        SIDE_EFFECT = s;
        STAT_LOWERED = null;
    }


    Move(String name, Type type, MoveType m, int power, int pp, int accuracy, Stat s)
    {
        NAME = name;
        TYPE = type;
        ACCURACY = accuracy;
        POWER = power;
        this.pp = pp;
        battlePP = pp;
        SIDE_EFFECT = null;
        STAT_LOWERED = s;
    }


    Move(String name, Type type, MoveType m, int power, int pp, int accuracy, Status status, Stat stat)
    {
        NAME = name;
        TYPE = type;
        ACCURACY = accuracy;
        POWER = power;
        this.pp = pp;
        battlePP = pp;
        ;
        SIDE_EFFECT = status;
        STAT_LOWERED = stat;
    }*/

    public Status getStatusEffect() {
        return SIDE_EFFECT;
    }

    public MoveType getMoveType()
    {
        return MOVE_TYPE;
    }

    public int getPower()
    {
        return POWER;
    }
    
    public void setPP(byte PP)
    {
        battlePP = PP;
    }
    
    public void downPP()
    {
        battlePP--;
    }
    
    public int getCurrentPP()
    {
        return battlePP;
    }
    
    public int getTotalPP()
    {
        return pp;
    }
    
    public void addPP(int PP)
    {
        battlePP += PP;
    }

    public void resetAccuracy()
    {
        battleAccuracy = ACCURACY;
    }

    public void resetPP()
    {
        battlePP = pp;
    }
    
    public String getName()
    {
        return NAME;
    }

    public Type getType()
    {
        return TYPE;
    }
    
    public int getAccuracy()
    {
        return ACCURACY;
    }

    @Override
    public String toString()
    {
        return NAME + "(" + TYPE + ", " + POWER + ", " + ACCURACY + ", (" + getCurrentPP() + " / " + getTotalPP() + ")";
    }
}